name = inputsdz("请输入你的姓名")
age = int(input("请输入你的年龄"))
sex = input("请输入你的性别")
height = int(input("请输入你的身高"))
weight = int(input("请输入你的体重"))
print("姓名:%s"%name)
print("年龄:%s"%int(age))
print("性别:%s"%sex)
print("身高:%s"%int(height))
print("体重:%s"%int(weight))
