name = input("请输入你的姓名")
age = input("请输入你的年龄")
sex = input("请输入你的性别")
hobby = input("请输入你的爱好")
family = input("请输入你的家庭成员")
position = input("请输入你的职位")
ID = input("请输入你的身份证号")
csny = input("请输入你的出生年月")
xl = input("请输入你的学历")
addr = input("请输入你的家庭地址")
tel = input("请输入你的电话号码")
mingzu = input("请输入你的民族")
country = input("请输入你的国籍")
print("姓名:%s"%name,"年龄:%s"%age,"性别:%s"%sex,"爱好:%s"%hobby,"家庭成员:%s"%family,"职位:%s"%position,"身份证号:%s"%str(ID),"出生年月:%s"%str(csny),"学历:%s"%xl,"家庭住址:%s"%addr,"电话:%s"%str(tel),"民族:%s"%mingzu,"国籍:%s"%country)
